In [5]:
import numpy as np
seq1='TTCATA'
seq2='TGCTCGTA'

In [6]:
matrix=np.zeros((len(seq1)+1,len(seq2)+1))

In [7]:
s_matrix=np.zeros((len(seq1),len(seq2)))
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if seq1[i]==seq2[j]:
            s_matrix[i][j]=1
        else:     
            s_matrix[i][j]=0
s_matrix

array([[1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [8]:
match_score=2
mismatch_score=-1
gap_penalty=-1

In [9]:
def Align(x,y):
	if x==y:
		return match_score
	elif x!= y:
		return mismatch_score	
	elif x == '-' or y == '-':
		return gap_penalty

In [10]:
def smith_waterman(matrix):
   for i in range(1,len(seq1)+1):
       for j in range(1,len(seq2)+1):
            value=max(matrix[i-1][j-1]+Align(seq1[i-1],seq2[j-1]),matrix[i-1][j]+gap_penalty,matrix[i][j-1]+gap_penalty,0)
            if value>=0:
                matrix[i][j]=value
   return(matrix)

In [11]:
smith_waterman(matrix)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 1., 0., 2., 1., 0., 2., 1.],
       [0., 2., 1., 0., 2., 1., 0., 2., 1.],
       [0., 1., 1., 3., 2., 4., 3., 2., 1.],
       [0., 0., 0., 2., 2., 3., 3., 2., 4.],
       [0., 2., 1., 1., 4., 3., 2., 5., 4.],
       [0., 1., 1., 0., 3., 3., 2., 4., 7.]])

In [12]:
def modified(matrix):
   for i in range(1,len(seq1)+1):
       for j in range(1,len(seq2)+1):
            value=max(matrix[i-1][j-1]+s_matrix[i-1][j-1],matrix[i-1][j]+gap_penalty,matrix[i][j-1]+gap_penalty)
            if value>=0:
                matrix[i][j]=value
   return(matrix)

In [13]:
modified(matrix)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [0., 0., 1., 2., 1., 2., 1., 0., 1.],
       [0., 0., 0., 1., 2., 1., 2., 1., 1.],
       [0., 1., 0., 0., 2., 2., 1., 3., 2.],
       [0., 0., 1., 0., 1., 2., 2., 2., 4.]])

In [14]:
m=matrix.shape[0]
k=matrix[m-1:m,:]
for i in range(k.shape[1]):
    if matrix[m-1][i]==np.amax(k):
        nl=i
nl

8

In [15]:
AlignmentA=""
AlignmentB=""
i=len(seq1)
j=nl
while(matrix[i,j]!=0 and (i>0 or j>0)):
  if (i > 0 and j > 0 and matrix[i][j] == matrix[i-1][j-1] + s_matrix[i-1][j-1]):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    i=i - 1
    j=j - 1

  elif (i > 0 and matrix[i][j] == matrix[i-1][j] + gap_penalty):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB="-" + AlignmentB
    i=i - 1
  
  else:
  
    AlignmentA="-" + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    j=j - 1

In [16]:
AlignmentA

'TCATA'

In [17]:
AlignmentB

'TCGTA'