In [46]:
import numpy as np
seq1='TTCATA'
seq2='TGCTCGTA'

In [47]:
matrix=np.zeros((len(seq1)+1,len(seq2)+1))

In [48]:
s_matrix=np.zeros((len(seq1),len(seq2)))
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if seq1[i]==seq2[j]:
            s_matrix[i][j]=1
        else:     
            s_matrix[i][j]=0
s_matrix

array([[1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
match_score=5
mismatch_score=-2
gap_penalty=-6

In [50]:
def Align(x,y):
	if x==y:
		return match_score
	elif x!= y:
		return mismatch_score	
	elif x == '-' or y == '-':
		return gap_penalty

In [51]:
def smith_waterman(matrix):
   for i in range(1,len(seq1)+1):
       for j in range(1,len(seq2)+1):
            value=max(matrix[i-1][j-1]+Align(seq1[i-1],seq2[j-1]),matrix[i-1][j]+gap_penalty,matrix[i][j-1]+gap_penalty,0)
            if value>=0:
                matrix[i][j]=value
   return(matrix)

In [52]:
smith_waterman(matrix)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  5.,  0.,  0.,  5.,  0.],
       [ 0.,  5.,  3.,  0.,  5.,  3.,  0.,  5.,  3.],
       [ 0.,  0.,  3.,  8.,  2., 10.,  4.,  0.,  3.],
       [ 0.,  0.,  0.,  2.,  6.,  4.,  8.,  2.,  5.],
       [ 0.,  5.,  0.,  0.,  7.,  4.,  2., 13.,  7.],
       [ 0.,  0.,  3.,  0.,  1.,  5.,  2.,  7., 18.]])

In [53]:
def modified(matrix):
   for i in range(1,len(seq1)+1):
       for j in range(1,len(seq2)+1):
            value=max(matrix[i-1][j-1]+s_matrix[i-1][j-1],matrix[i-1][j]+gap_penalty,matrix[i][j-1]+gap_penalty)
            if value>=0:
                matrix[i][j]=value
   return(matrix)

In [54]:
modified(matrix)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [0., 0., 1., 2., 0., 2., 1., 0., 1.],
       [0., 0., 0., 1., 2., 0., 2., 1., 1.],
       [0., 1., 0., 0., 2., 2., 0., 3., 1.],
       [0., 0., 1., 0., 0., 2., 2., 0., 4.]])

In [55]:
m=matrix.shape[0]
k=matrix[m-1:m,:]
for i in range(k.shape[1]):
    if matrix[m-1][i]==np.amax(k):
        nl=i

In [56]:
AlignmentA=""
AlignmentB=""
i=len(seq1)
j=nl
while(matrix[i,j]!=0 and (i>0 or j>0)):
  if (i > 0 and j > 0 and matrix[i][j] == matrix[i-1][j-1] + s_matrix[i-1][j-1]):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    i=i - 1
    j=j - 1

  elif (i > 0 and matrix[i][j] == matrix[i-1][j] + gap_penalty):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB="-" + AlignmentB
    i=i - 1
  
  else:
  
    AlignmentA="-" + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    j=j - 1

In [57]:
AlignmentA

'TCATA'

In [58]:
AlignmentB

'TCGTA'