In [31]:
import numpy as np


seq1='ATGGCTA'
seq2= 'ATAATTCA'


m = len(seq1)
n = len(seq2) 
score_mat = np.zeros((m+1, n+1), dtype=int)

match=1
gap= mismatch= -1
score_mat[0][0] = 0

for i in range(0,m+1):
	score_mat[i][0] = i * gap 
for j in range(0,n+1):
	score_mat[0][j] = j * gap 
s_matrix=np.zeros((len(seq1),len(seq2)))
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if seq1[i]==seq2[j]:
            s_matrix[i][j]=1
        else:     
            s_matrix[i][j]=0
print(s_matrix)
print (score_mat)


def Align(x,y):
	if x==y:
		return match
	elif x!= y:
		return mismatch	
	elif x == '-' or y == '-':
		return gap	

def NeedlemanWunchScoring(seq1, seq2, n, m):
	#fill the other entries of the matrix
	for i in range(1, m+1):
		for j in range(1, n+1):
			match  = score_mat[i-1][j-1] + Align(seq1[i-1], seq2[j-1])
			delete = score_mat[i-1][j]   +  gap
			insert = score_mat[i][j-1]   +  gap
			score_mat[i][j] = max(match, delete, insert)
			#print seq1[i-1], seq2[j-1], score_mat[i-1][j-1]
	return score_mat		


Final_mat=NeedlemanWunchScoring(seq1, seq2, n, m)

print ("seq1=", seq1 +"\n" + "seq2=", seq2)

print ('\n\nscore matrix \n')

print (Final_mat)

AlignmentA=""
AlignmentB=""
i=len(seq1)
j=len(seq2)
while (i >0 or j >0):

  if (i > 0 and j > 0 and score_mat[i][j] == score_mat[i-1][j-1] + s_matrix[i-1][j-1]):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    i=i - 1
    j=j - 1

  elif (i > 0 and score_mat[i][j] == score_mat[i-1][j] + gap):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB="-" + AlignmentB
    i=i - 1
  
  else:
  
    AlignmentA="-" + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    j=j - 1


[[1. 0. 1. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 1.]]
[[ 0 -1 -2 -3 -4 -5 -6 -7 -8]
 [-1  0  0  0  0  0  0  0  0]
 [-2  0  0  0  0  0  0  0  0]
 [-3  0  0  0  0  0  0  0  0]
 [-4  0  0  0  0  0  0  0  0]
 [-5  0  0  0  0  0  0  0  0]
 [-6  0  0  0  0  0  0  0  0]
 [-7  0  0  0  0  0  0  0  0]]
seq1= ATGGCTA
seq2= ATAATTCA


score matrix 

[[ 0 -1 -2 -3 -4 -5 -6 -7 -8]
 [-1  1  0 -1 -2 -3 -4 -5 -6]
 [-2  0  2  1  0 -1 -2 -3 -4]
 [-3 -1  1  1  0 -1 -2 -3 -4]
 [-4 -2  0  0  0 -1 -2 -3 -4]
 [-5 -3 -1 -1 -1 -1 -2 -1 -2]
 [-6 -4 -2 -2 -2  0  0 -1 -2]
 [-7 -5 -3 -1 -1 -1 -1 -1  0]]


In [32]:
 AlignmentA


'ATG-G-C-T-A'

In [33]:
AlignmentB



'AT-A-A-TTCA'