In [14]:
import pandas as pd
import numpy as np

gap_penalty=-2   #You can change this score 
match_score=2
mismatch_score=-3

def initialize(r,c):
    mat=np.zeros((r+1,c+1))
    mat[0]=[-i for i in range(len(mat[0]))]
    mat[:,0]=[-i for i in range(len(mat[:,0]))]
    return(mat)

def match(seq1,seq2):
    mat=np.ones((len(seq1),len(seq2)))
    for i in range(len(seq1)):
        for j in range(len(seq2)):
            if(seq1[i]==seq2[j]):
                mat[i,j]=match_score
            else:
                mat[i,j]=mismatch_score
    return(mat)

def backtrack(mat,seq1,seq2,match_table):
    s1=""
    s2=""
    i=len(seq1)
    j=len(seq2)
    while(i>0 or j>0):
        if(i>0 and j>0 and mat[i,j]==mat[i-1,j-1]+match_table[i-1,j-1]): #diagnol no align
            s1 = seq1[i-1] + s1
            s2 = seq2[j-1] + s2
            i = i-1
            j = j-1
        elif(i>0 and mat[i,j]==mat[i-1,j]+gap_penalty): #horizontal align in 2nd seq
            s1 = seq1[i-1] + s1
            s2 = '_' + s2
            i =i-1
        else: #vertical align in 1st seq
            s1 = '_' + s1
            s2 = seq2[j-1] + s2
            j =j-1            
    return(s1,s2)

def matrix(mat,match_table):
    for i in range(1,mat.shape[0]):
        for j in range(1,mat.shape[1]):
            a=mat[i-1,j]+gap_penalty
            b=mat[i,j-1]+gap_penalty
            c=mat[i-1,j-1]+match_table[i-1,j-1]
            mat[i,j]=max(a,b,c)
    return(mat)

def n_w(seq1,seq2):
    
    mat=initialize(len(seq1),len(seq2))
    match_table=match(seq1,seq2)
    mat=matrix(mat,match_table)
    alignment=backtrack(mat,seq1,seq2,match_table)
    print(mat)
    return(alignment)


print("Input is ('ACTGATTCA','ACGCATCA')")
print("Result is :",n_w('ACTGATTCA','ACGCATCA'))

Input is ('ACTGATTCA','ACGCATCA')
[[ 0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [-1.  2.  0. -2. -4. -2. -4. -6. -5.]
 [-2.  0.  4.  2.  0. -2. -4. -2. -4.]
 [-3. -2.  2.  1. -1. -3.  0. -2. -4.]
 [-4. -4.  0.  4.  2.  0. -2. -3. -5.]
 [-5. -2. -2.  2.  1.  4.  2.  0. -1.]
 [-6. -4. -4.  0. -1.  2.  6.  4.  2.]
 [-7. -6. -6. -2. -3.  0.  4.  3.  1.]
 [-8. -8. -4. -4.  0. -2.  2.  6.  4.]
 [-9. -6. -6. -6. -2.  2.  0.  4.  8.]]
Result is : ('ACTG_ATTCA', 'AC_GCA_TCA')
